### ISSUE TITLE
Vi må fikse produktsidene

### ISSUE THREAD

**Issue by respiant** [respiant/weboblig2#3]
For liten font størrelse på produktsidene, så blir veldig smått.
Kanskje skille pris fra resten av beskrivelsen?

**Comment by BioExe** [comment]
skille pris, kanskje også legge inn en mindre versjon av bilde av produktet på selve produktsiden?

**Comment by respiant** [comment]
Og linken til produktsidene, som f.eks:
index.php?product_id=PRODUKT

der bør "PRODUKT" være beskrivende for produktet, fordi "PRODUKT" brukes som tittel på produktsiden.
